[application]

[web.app]

# HTML title tag content
title = "evaporate"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []


[bundle]
identifier="goglike.goglikestudios"
publisher="Georgii Krikun"
icon=["/home/georgii/software/dioxus-test/evaporate/assets/happy.png"]
